; Wave 3 social command handlers (separate link unit).
; Generated by tools/gen_social_port3.py -- regenerate if social.c rules change.
default rel
%include "state.inc"

%define RESCUED_ROW_SIZE 128
%define FALLEN_ROW_SIZE 128
%define LEDGER_ROW_SIZE 36

section .text

extern snprintf, strlen, strcpy, strncpy, strcasecmp, strncasecmp, strcmp, memset, atoll
extern hg_queue_line, hg_queue_cstr, hg_deliver_room, hg_deliver_all, hg_json_escape, hg_is_admin
extern hg_emit_vitals_now, hg_emit_affects_now, hg_emit_room_actions_now, hg_store_save, hg_room_id_cstr
extern hg_now_ms, hg_grid_record_local_echo, hg_grid_shift_tide, hg_grid_gridcast
extern hg_grid_record_rescued, hg_grid_recent_rescued, hg_grid_recent_fallen
extern hg_grid_ledger_stats, hg_grid_prune_ledger
extern hg_deed_add_str, hg_forgiven_has, hg_forgiven_mark, hg_kept_has, hg_kept_mark
extern hg_add_deed_h
extern hg_cells_ready_at_get, hg_cells_ready_at_set, hg_transit_ready_at_get, hg_transit_ready_at_set
extern hg_moral_arc_now, resolve_return_h
extern setup_cmd, queue_line_h, queue_cstr_h, skip_spaces, find_player_prefix
extern inv_add_internal, inv_find_slot
extern hg_emit_comm_gridcast_now, hg_emit_saved_roll_now, hg_emit_fallen_roll_now
extern hg_emit_gridstats_cmd_now, hg_emit_gridprune_cmd_now
extern hg_emit_forgiven_target_now, hg_emit_forgiven_redeemed_now

global hg_cmd_free, hg_cmd_gridcast, hg_cmd_shelter, hg_cmd_saved
global hg_dais_pledge, hg_cmd_defy, hg_cmd_forgive, hg_cmd_witness
global hg_cmd_gridstats, hg_cmd_gridprune

; Align stack for C after setup_cmd (entry rsp%16==0 from asm caller).
%macro CMD_ALIGN 0
    sub rsp, 8
%endmacro
%macro CMD_UNALIGN 0
    add rsp, 8
%endmacro

; Parse first word from rdx into [rsp+16] (40 bytes). Returns rax=1 if non-empty.
parse_word_h:
    push rbx
    push r12
    sub rsp, 8
    mov r12, rdx
    test r12, r12
    jz .empty
    mov rdi, r12
    call skip_spaces
    mov r12, rax
    cmp byte [r12], 0
    je .empty
    xor ebx, ebx
.loop:
    movzx eax, byte [r12 + rbx]
    test al, al
    jz .done
    cmp al, ' '
    je .done
    cmp ebx, 38
    jge .done
    mov [rsp + 16 + rbx], al
    inc ebx
    jmp .loop
.done:
    mov byte [rsp + 16 + rbx], 0
    mov eax, 1
    jmp .out
.empty:
    xor eax, eax
.out:
    add rsp, 8
    pop r12
    pop rbx
    ret


; --- free -------------------------------------------------------------------
hg_cmd_free:
    call setup_cmd
    CMD_ALIGN
    mov rax, [r12 + SESSION_ROOM]
    cmp rax, ROOM_HOLDING_PIT
    je .pit
    cmp rax, ROOM_CELLS
    je .cells
    mov rdi, r12
    lea rsi, [rel sp2_free_none]
    call queue_line_h
    CMD_UNALIGN
    ret
.pit:
    mov rdi, r12
    lea rsi, [rel sp2_antidote]
    call inv_find_slot
    test eax, eax
    jns .have_vial
    mov rdi, r12
    lea rsi, [rel sp2_antidote]
    call inv_add_internal
    add qword [r12 + SESSION_MORALITY], 12
    lea rdi, [r12 + SESSION_LAST_FREED]
    cmp byte [rdi], 0
    jne .pit_deed
    lea rsi, [rel sp2_mira]
    mov edx, 40
    call strncpy wrt ..plt
.pit_deed:
    lea rdi, [r12 + SESSION_NAME]
    mov esi, DEED_FREED
    call hg_add_deed_h
    sub rsp, 400
    mov rdi, r12
    call hg_now_ms wrt ..plt
    mov r14, rax
    lea rdi, [rel sp2_basalt]
    lea rsi, [rel sp2_mira]
    lea rdx, [r12 + SESSION_NAME]
    mov rcx, r14
    call hg_grid_record_rescued wrt ..plt
    mov rdi, rsp
    mov esi, 320
    lea rdx, [rel sp2_free_pit]
    lea rcx, [rel sp2_mira]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    mov rsi, rsp
    call queue_line_h
    lea rdi, [rsp + 160]
    mov esi, 80
    lea rdx, [r12 + SESSION_NAME]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 240]
    mov esi, 80
    lea rdx, [rel sp2_mira]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 320]
    mov esi, 80
    lea rdx, [rel sp2_rescued_one]
    lea rcx, [rsp + 160]
    lea r8, [rsp + 240]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 320]
    call queue_cstr_h
    xor edi, edi
    xor esi, esi
    call hg_grid_shift_tide wrt ..plt
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    mov rdi, r12
    call hg_store_save wrt ..plt
    add rsp, 400
    CMD_UNALIGN
    ret
.have_vial:
    mov rdi, r12
    lea rsi, [rel sp2_free_have]
    call queue_line_h
    CMD_UNALIGN
    ret
.cells:
    mov rdi, r12
    call hg_now_ms wrt ..plt
    mov r14, rax
    call hg_cells_ready_at_get
    cmp rax, r14
    jg .cells_empty
    mov rdi, r14
    add rdi, 3600000
    call hg_cells_ready_at_set
    lea rdi, [r12 + SESSION_LAST_FREED]
    cmp byte [rdi], 0
    jne .cells_deed
    lea rsi, [rel sp2_rook]
    mov edx, 40
    call strncpy wrt ..plt
.cells_deed:
    lea rdi, [r12 + SESSION_NAME]
    mov esi, DEED_FREED
    call hg_add_deed_h
    lea rdi, [rel sp2_basalt]
    lea rsi, [rel sp2_rook]
    lea rdx, [r12 + SESSION_NAME]
    mov rcx, r14
    call hg_grid_record_rescued wrt ..plt
    lea rdi, [rel sp2_basalt]
    lea rsi, [rel sp2_sable]
    lea rdx, [r12 + SESSION_NAME]
    mov rcx, r14
    call hg_grid_record_rescued wrt ..plt
    add qword [r12 + SESSION_MORALITY], 15
    mov rdi, r12
    lea rsi, [rel sp2_free_cells]
    call queue_cstr_h
    ; esc@0(80) evt@80(160) = 240; keep inside the frame (old +240/80 smashed ret)
    sub rsp, 240
    mov rdi, rsp
    mov esi, 80
    lea rdx, [r12 + SESSION_NAME]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 80]
    mov esi, 160
    lea rdx, [rel sp2_rescued_two]
    mov rcx, rsp
    lea r8, [rel sp2_rook]
    lea r9, [rel sp2_sable]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 80]
    call queue_cstr_h
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    mov rdi, r12
    call hg_store_save wrt ..plt
    add rsp, 240
    CMD_UNALIGN
    ret
.cells_empty:
    mov rdi, r12
    lea rsi, [rel sp2_free_empty]
    call queue_line_h
    CMD_UNALIGN
    ret

; --- gridcast ---------------------------------------------------------------
hg_cmd_gridcast:
    call setup_cmd
    CMD_ALIGN
    mov rdi, rdx
    call skip_spaces
    mov r14, rax
    cmp byte [r14], 0
    je .need
    lea rdi, [r12 + SESSION_NAME]
    mov rsi, r14
    call hg_grid_gridcast wrt ..plt
    test eax, eax
    jnz .fail
    ; r14 still holds the message text (eax is 0 on success)
    sub rsp, 320
    mov rdi, rsp
    mov esi, 280
    lea rdx, [rel sp2_gridcast_prose]
    mov rcx, r14
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    mov rsi, rsp
    call queue_line_h
    mov rdi, r12
    mov rsi, r14
    call hg_emit_comm_gridcast_now wrt ..plt
    add rsp, 320
    CMD_UNALIGN
    ret
.need:
    mov rdi, r12
    lea rsi, [rel sp2_gridcast_need]
    call queue_line_h
    CMD_UNALIGN
    ret
.fail:
    mov rdi, r12
    lea rsi, [rel sp2_gridcast_fail]
    call queue_line_h
    CMD_UNALIGN
    ret

; --- shelter ----------------------------------------------------------------
hg_cmd_shelter:
    call setup_cmd
    CMD_ALIGN
    mov rax, [r12 + SESSION_ROOM]
    cmp rax, ROOM_TRANSIT_HUB
    jne .wrong
    mov rdi, r12
    call hg_now_ms wrt ..plt
    mov r14, rax
    call hg_transit_ready_at_get
    cmp rax, r14
    jg .empty
    mov rdi, r14
    add rdi, 3600000
    call hg_transit_ready_at_set
    lea rdi, [r12 + SESSION_LAST_FREED]
    cmp byte [rdi], 0
    jne .sh_deed
    lea rsi, [rel sp2_tess]
    mov edx, 40
    call strncpy wrt ..plt
.sh_deed:
    lea rdi, [r12 + SESSION_NAME]
    mov esi, DEED_SHELTERED
    call hg_add_deed_h
    lea rdi, [rel sp2_basalt]
    lea rsi, [rel sp2_tess]
    lea rdx, [r12 + SESSION_NAME]
    mov rcx, r14
    call hg_grid_record_rescued wrt ..plt
    lea rdi, [rel sp2_basalt]
    lea rsi, [rel sp2_jon]
    lea rdx, [r12 + SESSION_NAME]
    mov rcx, r14
    call hg_grid_record_rescued wrt ..plt
    add qword [r12 + SESSION_MORALITY], 15
    mov rdi, r12
    lea rsi, [rel sp2_shelter_prose]
    call queue_cstr_h
    ; esc@0(80) evt@80(160) = 240; keep inside the frame (old +240/80 smashed ret)
    sub rsp, 240
    mov rdi, rsp
    mov esi, 80
    lea rdx, [r12 + SESSION_NAME]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 80]
    mov esi, 160
    lea rdx, [rel sp2_rescued_two]
    mov rcx, rsp
    lea r8, [rel sp2_tess]
    lea r9, [rel sp2_jon]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 80]
    call queue_cstr_h
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    mov rdi, r12
    call hg_store_save wrt ..plt
    add rsp, 240
    CMD_UNALIGN
    ret
.wrong:
    mov rdi, r12
    lea rsi, [rel sp2_shelter_wrong]
    call queue_line_h
    CMD_UNALIGN
    ret
.empty:
    mov rdi, r12
    lea rsi, [rel sp2_shelter_empty]
    call queue_line_h
    CMD_UNALIGN
    ret

; --- saved / witness / gridstats / gridprune / forgive (rules in asm) ---
hg_cmd_saved:
    call setup_cmd
    CMD_ALIGN
    mov rdi, r12
    call hg_emit_saved_roll_now wrt ..plt
    CMD_UNALIGN
    ret

hg_cmd_gridstats:
    call setup_cmd
    CMD_ALIGN
    lea rdi, [r12 + SESSION_NAME]
    call hg_is_admin wrt ..plt
    test eax, eax
    jz .deny
    mov rdi, r12
    call hg_emit_gridstats_cmd_now wrt ..plt
    CMD_UNALIGN
    ret
.deny:
    mov rdi, r12
    lea rsi, [rel sp2_stats_deny]
    call queue_line_h
    CMD_UNALIGN
    ret

hg_cmd_gridprune:
    call setup_cmd
    CMD_ALIGN
    lea rdi, [r12 + SESSION_NAME]
    call hg_is_admin wrt ..plt
    test eax, eax
    jz .deny
    mov rdi, r12
    call hg_emit_gridprune_cmd_now wrt ..plt
    CMD_UNALIGN
    ret
.deny:
    mov rdi, r12
    lea rsi, [rel sp2_prune_deny]
    call queue_line_h
    CMD_UNALIGN
    ret

; --- forgive (ledger, morality, deeds, redemption title) --------------------
hg_cmd_forgive:
    call setup_cmd
    CMD_ALIGN
    push rbx
    push r14
    push r15
    sub rsp, 200
    mov rdi, rdx
    test rdi, rdi
    jz .need
    call skip_spaces
    mov r14, rax
    cmp byte [r14], 0
    je .need
    xor ebx, ebx
.pw:
    movzx eax, byte [r14 + rbx]
    test al, al
    jz .pw_done
    cmp al, ' '
    je .pw_done
    cmp ebx, 38
    jge .pw_done
    mov [rsp + rbx], al
    inc ebx
    jmp .pw
.pw_done:
    mov byte [rsp + rbx], 0
    test ebx, ebx
    jz .need
    lea rdi, [rsp]
    lea rsi, [r12 + SESSION_NAME]
    call strcasecmp wrt ..plt
    test eax, eax
    jz .self
    mov rdi, [r12 + SESSION_ROOM]
    lea rsi, [rsp]
    xor edx, edx
    call find_player_prefix
    test rax, rax
    jz .absent
    mov r15, rax
    lea rdi, [r12 + SESSION_NAME]
    lea rsi, [r15 + SESSION_NAME]
    call hg_forgiven_has wrt ..plt
    test eax, eax
    jnz .twice
    cmp qword [r15 + SESSION_ASHSWORN], 0
    jne .marked
    cmp qword [r15 + SESSION_STRAYED], 0
    jne .marked
    lea rdi, [r15 + SESSION_FACTION]
    lea rsi, [rel sp2_front]
    call strcmp wrt ..plt
    test eax, eax
    jz .marked
    mov rax, [r15 + SESSION_MORALITY]
    cmp rax, -50
    jg .unmarked
.marked:
    lea rdi, [r12 + SESSION_NAME]
    lea rsi, [r15 + SESSION_NAME]
    call hg_forgiven_mark wrt ..plt
    lea rdi, [r12 + SESSION_NAME]
    lea rsi, [rel sp2_dforgave]
    call hg_deed_add_str wrt ..plt
    add qword [r15 + SESSION_MORALITY], 5
    add qword [r12 + SESSION_MORALITY], 2
    lea rdi, [rsp + 40]
    mov esi, 160
    lea rdx, [rel sp2_grace]
    lea rcx, [r12 + SESSION_NAME]
    lea r8, [r15 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, [r12 + SESSION_ROOM]
    call hg_room_id_cstr wrt ..plt
    test rax, rax
    jnz .grace_node
    lea rax, [rel sp2_market]
.grace_node:
    mov rdi, rax
    lea rsi, [rel sp2_grace_kind]
    lea rdx, [rsp + 40]
    call hg_grid_record_local_echo wrt ..plt
    cmp qword [r15 + SESSION_ASHSWORN], 0
    jne .ash_path
    cmp qword [r15 + SESSION_STRAYED], 0
    je .plain_path
    cmp qword [r15 + SESSION_REDEEMED], 0
    jne .plain_path
    lea rdi, [r15 + SESSION_FACTION]
    lea rsi, [rel sp2_front]
    call strcmp wrt ..plt
    test eax, eax
    jz .plain_path
    mov qword [r15 + SESSION_REDEEMED], 1
    cmp byte [r15 + SESSION_TITLE], 0
    jne .save_redeem
    lea rdi, [r15 + SESSION_TITLE]
    lea rsi, [rel sp2_returned]
    mov edx, 48
    call strncpy wrt ..plt
    mov byte [r15 + SESSION_TITLE + 47], 0
.save_redeem:
    mov rdi, r15
    call hg_store_save wrt ..plt
    mov rdi, r15
    mov rsi, r12
    call hg_emit_forgiven_redeemed_now wrt ..plt
    jmp .room_announce
.ash_path:
    mov rdi, r15
    mov rsi, r12
    mov edx, 1
    xor ecx, ecx
    call hg_emit_forgiven_target_now wrt ..plt
    jmp .room_announce
.plain_path:
    mov rdi, r15
    mov rsi, r12
    xor edx, edx
    xor ecx, ecx
    call hg_emit_forgiven_target_now wrt ..plt
.room_announce:
    lea rdi, [rsp + 40]
    mov esi, 160
    lea rdx, [rel sp2_forgive_room]
    lea rcx, [r12 + SESSION_NAME]
    lea r8, [r15 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, [r12 + SESSION_ROOM]
    lea rsi, [rsp + 40]
    lea rdx, [r12 + SESSION_NAME]
    call hg_deliver_room wrt ..plt
    lea rdi, [rsp + 40]
    mov esi, 160
    lea rdx, [rel sp2_forgive_you]
    lea rcx, [r15 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 40]
    call queue_line_h
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    add rsp, 200
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret
.need:
    mov rdi, r12
    lea rsi, [rel sp2_forgive_need]
    call queue_line_h
    add rsp, 200
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret
.self:
    mov rdi, r12
    lea rsi, [rel sp2_forgive_self]
    call queue_line_h
    add rsp, 200
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret
.absent:
    lea rdi, [rsp + 40]
    mov esi, 120
    lea rdx, [rel sp2_forgive_absent]
    lea rcx, [rsp]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 40]
    call queue_line_h
    add rsp, 200
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret
.twice:
    lea rdi, [rsp + 40]
    mov esi, 160
    lea rdx, [rel sp2_forgive_twice]
    lea rcx, [r15 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 40]
    call queue_line_h
    add rsp, 200
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret
.unmarked:
    lea rdi, [rsp + 40]
    mov esi, 160
    lea rdx, [rel sp2_forgive_unmarked]
    lea rcx, [r15 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 40]
    call queue_line_h
    add rsp, 200
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret

; --- witness (keep fallen memory; roll presentation via format) ------------
hg_cmd_witness:
    call setup_cmd
    CMD_ALIGN
    push rbx
    push r14
    push r15
    ; layout: who[40] @0, fallen[12*128] @64, count@1600,
    ; scratch/escapes @1608 (40+48+40), evt @1744 (280). Frame 2040 (align).
    sub rsp, 2040
    mov byte [rsp], 0
    mov rdi, rdx
    test rdi, rdi
    jz .have_word
    call skip_spaces
    mov r14, rax
    cmp byte [r14], 0
    je .have_word
    xor ebx, ebx
.pw:
    movzx eax, byte [r14 + rbx]
    test al, al
    jz .pw_done
    cmp al, ' '
    je .pw_done
    cmp ebx, 38
    jge .pw_done
    mov [rsp + rbx], al
    inc ebx
    jmp .pw
.pw_done:
    mov byte [rsp + rbx], 0
.have_word:
    mov qword [rsp + 1600], 0
    mov edi, 12
    lea rsi, [rsp + 64]
    mov edx, 12
    lea rcx, [rsp + 1600]
    call hg_grid_recent_fallen wrt ..plt
    cmp byte [rsp], 0
    jne .named
    mov rdi, r12
    call hg_emit_fallen_roll_now wrt ..plt
    jmp .done
.named:
    lea rdi, [rsp]
    lea rsi, [r12 + SESSION_NAME]
    call strcasecmp wrt ..plt
    test eax, eax
    jz .self
    mov r15, [rsp + 1600]
    xor ebx, ebx
    xor r14, r14
.find:
    cmp rbx, r15
    jae .find_done
    imul rax, rbx, 128
    lea rdi, [rsp + 64 + rax + 48]
    lea rsi, [rsp]
    call strcasecmp wrt ..plt
    test eax, eax
    jnz .next
    imul rax, rbx, 128
    lea r14, [rsp + 64 + rax]
    jmp .find_done
.next:
    inc ebx
    jmp .find
.find_done:
    test r14, r14
    jz .absent
    lea rdi, [r12 + SESSION_NAME]
    lea rsi, [r14 + 48]
    call hg_kept_has wrt ..plt
    test eax, eax
    jnz .twice
    lea rdi, [r12 + SESSION_NAME]
    lea rsi, [r14 + 48]
    call hg_kept_mark wrt ..plt
    add qword [r12 + SESSION_MORALITY], 2
    lea rdi, [r12 + SESSION_NAME]
    lea rsi, [rel sp2_dkept]
    call hg_deed_add_str wrt ..plt
    mov rdi, r12
    call hg_store_save wrt ..plt
    lea rdi, [rsp + 1608]
    mov esi, 160
    lea rdx, [rel sp2_vigil_echo]
    lea rcx, [r12 + SESSION_NAME]
    lea r8, [r14 + 48]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, [r12 + SESSION_ROOM]
    call hg_room_id_cstr wrt ..plt
    test rax, rax
    jnz .vigil_node
    lea rax, [rel sp2_waystation]
.vigil_node:
    mov rdi, rax
    lea rsi, [rel sp2_vigil_kind]
    lea rdx, [rsp + 1608]
    call hg_grid_record_local_echo wrt ..plt
    lea rdi, [rsp + 1608]
    mov esi, 160
    lea rdx, [rel sp2_witness_prose]
    lea rcx, [r14 + 48]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 1608]
    call queue_line_h
    lea rdi, [rsp + 1608]
    mov esi, 40
    lea rdx, [r14 + 48]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 1648]
    mov esi, 48
    lea rdx, [r14]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 1696]
    mov esi, 40
    lea rdx, [r14 + 81]
    call hg_json_escape wrt ..plt
    lea rdi, [rsp + 1744]
    mov esi, 280
    lea rdx, [rel sp2_remembrance_evt]
    lea rcx, [rsp + 1608]
    lea r8, [rsp + 1648]
    lea r9, [rsp + 1696]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 1744]
    call queue_cstr_h
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    jmp .done
.self:
    mov rdi, r12
    lea rsi, [rel sp2_witness_self]
    call queue_line_h
    jmp .done
.absent:
    lea rdi, [rsp + 1608]
    mov esi, 160
    lea rdx, [rel sp2_witness_absent]
    lea rcx, [rsp]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 1608]
    call queue_line_h
    jmp .done
.twice:
    lea rdi, [rsp + 1608]
    mov esi, 160
    lea rdx, [rel sp2_witness_twice]
    lea rcx, [r14 + 48]
    xor eax, eax
    call snprintf wrt ..plt
    mov rdi, r12
    lea rsi, [rsp + 1608]
    call queue_line_h
.done:
    add rsp, 2040
    pop r15
    pop r14
    pop rbx
    CMD_UNALIGN
    ret

; --- dais pledge ------------------------------------------------------------
global hg_dais_pledge
hg_dais_pledge:
    mov r12, rdi
    CMD_ALIGN
    cmp qword [r12 + SESSION_ROOM], ROOM_DAIS
    jne .none
    lea rdi, [r12 + SESSION_FACTION]
    lea rsi, [rel sp2_none]
    call strcmp wrt ..plt
    jnz .settled
    lea rdi, [r12 + SESSION_FACTION]
    lea rsi, [rel sp2_front]
    mov edx, 16
    call strncpy wrt ..plt
    lea rdi, [r12 + SESSION_RACE]
    lea rsi, [rel sp2_elf]
    call strcasecmp wrt ..plt
    test eax, eax
    jz .hunted
    lea rdi, [r12 + SESSION_RACE]
    lea rsi, [rel sp2_dustkin]
    call strcasecmp wrt ..plt
    test eax, eax
    jnz .plain
.hunted:
    mov qword [r12 + SESSION_ASHSWORN], 1
    sub qword [r12 + SESSION_MORALITY], 40
    mov rdi, r12
    lea rsi, [rel sp2_dais_ash]
    call queue_cstr_h
    jmp .pledge_done
.plain:
    sub qword [r12 + SESSION_MORALITY], 25
    mov rdi, r12
    lea rsi, [rel sp2_dais_plain]
    call queue_line_h
.pledge_done:
    lea rdi, [r12 + SESSION_NAME]
    mov esi, DEED_PLEDGED
    call hg_add_deed_h
    xor edi, edi
    mov esi, -10
    call hg_grid_shift_tide wrt ..plt
    ; echo@0(160) shout@160(160) = 320; old 208-byte frame smashed ret on shout
    sub rsp, 320
    mov rdi, rsp
    mov esi, 160
    lea rdx, [rel sp2_pledge_echo]
    lea rcx, [r12 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    lea rdi, [rel sp2_dais]
    lea rsi, [rel sp2_oath_kind]
    mov rdx, rsp
    call hg_grid_record_local_echo wrt ..plt
    mov rdi, r12
    call hg_store_save wrt ..plt
    lea rdi, [rsp + 160]
    mov esi, 160
    lea rdx, [rel sp2_pledge_shout]
    lea rcx, [r12 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov edi, ROOM_DAIS
    lea rsi, [rsp + 160]
    lea rdx, [r12 + SESSION_NAME]
    call hg_deliver_room wrt ..plt
    mov rdi, r12
    call hg_moral_arc_now wrt ..plt
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    mov rdi, r12
    lea rsi, [rel sp2_dais]
    call hg_emit_vitals_now wrt ..plt
    mov rdi, r12
    call hg_emit_room_actions_now wrt ..plt
    add rsp, 320
    CMD_UNALIGN
    ret
.none:
    mov rdi, r12
    lea rsi, [rel sp2_dais_none]
    call queue_line_h
    CMD_UNALIGN
    ret
.settled:
    mov rdi, r12
    lea rsi, [rel sp2_dais_settled]
    call queue_line_h
    CMD_UNALIGN
    ret
sp2_oath_kind: db "oath", 0

; --- defy -------------------------------------------------------------------
hg_cmd_defy:
    call setup_cmd
    CMD_ALIGN
    cmp qword [r12 + SESSION_ROOM], ROOM_DAIS
    jne .none
    lea rdi, [r12 + SESSION_FACTION]
    lea rsi, [rel sp2_front]
    call strcmp wrt ..plt
    jnz .none
    lea rdi, [r12 + SESSION_FACTION]
    lea rsi, [rel sp2_ally]
    mov edx, 16
    call strncpy wrt ..plt
    add qword [r12 + SESSION_MORALITY], 30
    cmp qword [r12 + SESSION_ASHSWORN], 0
    jne .ash
    mov rdi, r12
    lea rsi, [rel sp2_defy_plain]
    call queue_cstr_h
    jmp .defy_done
.ash:
    mov rdi, r12
    lea rsi, [rel sp2_defy_ash]
    call queue_cstr_h
.defy_done:
    lea rdi, [r12 + SESSION_NAME]
    mov esi, DEED_DEFECTED
    call hg_add_deed_h
    xor edi, edi
    mov esi, 10
    call hg_grid_shift_tide wrt ..plt
    sub rsp, 320
    mov rdi, rsp
    mov esi, 160
    lea rdx, [rel sp2_defy_echo]
    lea rcx, [r12 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    lea rdi, [rel sp2_dais]
    lea rsi, [rel sp2_oath_kind]
    mov rdx, rsp
    call hg_grid_record_local_echo wrt ..plt
    mov rdi, r12
    call hg_store_save wrt ..plt
    lea rdi, [rsp + 160]
    mov esi, 160
    lea rdx, [rel sp2_defy_shout]
    lea rcx, [r12 + SESSION_NAME]
    xor eax, eax
    call snprintf wrt ..plt
    mov edi, ROOM_DAIS
    lea rsi, [rsp + 160]
    lea rdx, [r12 + SESSION_NAME]
    call hg_deliver_room wrt ..plt
    cmp qword [r12 + SESSION_STRAYED], 0
    je .moral
    cmp qword [r12 + SESSION_REDEEMED], 0
    jne .moral
    cmp qword [r12 + SESSION_ASHSWORN], 0
    jne .moral
    mov rax, [r12 + SESSION_MORALITY]
    cmp rax, REDEEM_CEIL
    jl .moral
    call resolve_return_h
    jmp .defy_emit
.moral:
    mov rdi, r12
    call hg_moral_arc_now wrt ..plt
.defy_emit:
    mov rdi, r12
    call hg_emit_affects_now wrt ..plt
    mov rdi, r12
    lea rsi, [rel sp2_dais]
    call hg_emit_vitals_now wrt ..plt
    mov rdi, r12
    call hg_emit_room_actions_now wrt ..plt
    add rsp, 320
    CMD_UNALIGN
    ret
.none:
    mov rdi, r12
    lea rsi, [rel sp2_defy_none]
    call queue_line_h
    CMD_UNALIGN
    ret

sp2_grace_kind: db "grace", 0
sp2_vigil_kind: db "vigil", 0
sp2_stats_deny: db "Only a keeper of the Grid can read its deep memory.", 0
sp2_prune_deny: db "Only a keeper of the Grid can tend its deep memory.", 0
sp2_dforgave: db "forgave", 0
sp2_dkept: db "kept", 0
sp2_vigil_echo: db "%s kept the memory of %s, whom the wastes tried to forget.", 0
sp2_witness_self: db "You cannot hold a vigil for yourself. Someone else will have to remember you.", 0
sp2_witness_absent: db "The Grid holds no recent memory of anyone called ", 34, "%s", 34, ".  (try 'witness' to read the roll)", 0
sp2_witness_twice: db "You have already kept %s's memory. It does not fade, and does not need keeping twice.", 0
sp2_witness_prose: db "You speak %s into the hum and hold it there a moment. The Grid keeps the name; so do you.", 0
sp2_remembrance_evt: db "@event grid.remembrance {", 34, "fallen", 34, ":", 34, "%s", 34, ",", 34, "world", 34, ":", 34, "%s", 34, ",", 34, "room", 34, ":", 34, "%s", 34, "}", 13, 10, 0

section .rodata
sp2_basalt: db "Basalt Relay", 0
sp2_market: db "market", 0
sp2_dais: db "dais", 0
sp2_nexus: db "nexus", 0
sp2_waystation: db "waystation", 0
sp2_front: db "front", 0
sp2_ally: db "ally", 0
sp2_none: db "none", 0
sp2_returned: db "the Returned", 0
sp2_antidote: db "antidote", 0
sp2_elf: db "elf", 0
sp2_dustkin: db "dustkin", 0
sp2_mira: db "Mira", 0
sp2_rook: db "Rook", 0
sp2_sable: db "Sable", 0
sp2_tess: db "Tess", 0
sp2_jon: db "Jon", 0
sp2_free_have: db "The maiden smiles weakly. ", 34, "You already carry my vial. Use it well.", 34, 0
sp2_free_pit: db "You strike the chains free. The captive presses a vial into your hands:", 13, 10, "  ", 34, "Antivenom, for the poison that haunts these wastes. My name is %s. I won't forget yours.", 34, 0
sp2_free_empty: db "The cages stand open and empty; someone already cut them loose. The Front will round up more soon enough -- it always does -- but not yet.", 0
sp2_free_cells: db "You wrench the cages open. Rook and Sable stumble out into the dark, some pausing only to grip your hand on the way past. Whatever else you are, whatever else you've done -- you did this.", 13, 10, 0
sp2_free_none: db "There is no one here to free.", 0
sp2_rescued_one: db "@event grid.rescued {", 34, "savedBy", 34, ":", 34, "%s", 34, ",", 34, "freed", 34, ":[", 34, "%s", 34, "]}", 13, 10, 0
sp2_rescued_two: db "@event grid.rescued {", 34, "savedBy", 34, ":", 34, "%s", 34, ",", 34, "freed", 34, ":[", 34, "%s", 34, ",", 34, "%s", 34, "]}", 13, 10, 0
sp2_gridcast_need: db "Gridcast what? (gridcast <message> -- the dead network carries it to every world)", 0
sp2_gridcast_fail: db "The Grid swallows your words; the network is unreachable.", 0
sp2_gridcast_prose: db "You cast your voice into the dead Grid, out across every node: ", 34, "%s", 34, 0
sp2_shelter_wrong: db "There's no one here to shelter. The distress call comes from the old transit hub, south off the Scorch Road.", 0
sp2_shelter_empty: db "The platform is empty now. Whoever called, you got them moving -- toward the free camp, you have to believe. The Front will strand others here soon enough; it always does, and the call will go out again.", 0
sp2_shelter_prose: db "You answer the call. You get Tess and Jon up and moving -- bottles filled at the tap, the youngest carried -- and stand watch on the cracked platform while they slip out the far side, toward the free camp and whatever the free folk can spare. The hand-radio goes quiet at last. Someone came.", 13, 10, 0
sp2_dais_none: db "There is no one here to swear to.", 0
sp2_dais_settled: db "The Ashmonger only laughs. There's nothing here to decide that your blood hasn't already settled.", 0
sp2_dais_ash: db "You kneel before the Ashmonger -- an elf, at the feet of the man who cages elves.", 13, 10, "He laughs, delighted, and burns the ash-and-flame into your shoulder with his own hand.", 13, 10, 34, "The best dogs are the ones who hate themselves. You'll do the work my men won't.", 34, 13, 10, "You are ash-sworn now. There is no one left to belong to.", 13, 10, 0
sp2_dais_plain: db "You kneel and swear yourself to the Front. The Ashmonger's hand closes on your shoulder like a trap. ", 34, "Good. The wastes will be ours.", 34, 0
sp2_pledge_echo: db "%s swore themselves to the Cinder Front at the Ashmonger's dais.", 0
sp2_pledge_shout: db "%s swore themselves to the Cinder Front at the Ashmonger's dais.", 13, 10, 0
sp2_defy_none: db "There's no oath here to break.", 0
sp2_defy_ash: db "You spit at the Ashmonger's boots. ", 34, "I'm done being your dog.", 34, " The stronghold turns on you at once.", 13, 10, "You stand with the free folk now -- but the brand on your shoulder stays. For once you wear it turning the right way.", 13, 10, "Whether the people you helped cage can ever look at you again is not a thing the wastes will settle tonight, or maybe ever. You turned. It has to be enough to start.", 13, 10, 0
sp2_defy_plain: db "You spit at the Ashmonger's boots. ", 34, "I'm done being your dog.", 34, " Every soldier in the stronghold turns on you at once -- but you stand with the free folk now, and the wastes will remember THIS above all.", 13, 10, 0
sp2_defy_echo: db "%s turned on the Cinder Front at the Ashmonger's own dais.", 0
sp2_defy_shout: db "%s has turned against the Cinder Front!", 13, 10, 0
sp2_forgive_need: db "Forgive whom?  (forgive <player> -- choose to let someone marked back in)", 0
sp2_forgive_self: db "You cannot forgive yourself here; that is a longer road, and a lonelier one.", 0
sp2_forgive_absent: db "There's no one called ", 34, "%s", 34, " here to forgive.", 0
sp2_forgive_twice: db "You have already forgiven %s. It was true the first time; it does not need saying twice.", 0
sp2_forgive_unmarked: db "%s carries nothing that needs your forgiveness. Keep the words for someone who does.", 0
sp2_grace: db "%s forgave %s here.", 0
sp2_forgive_push: db "%s looks at you and chooses to forgive you.", 13, 10, 0
sp2_forgive_room: db "%s forgives %s.", 13, 10, 0
sp2_forgive_you: db "You choose to forgive %s. Out here that is not nothing; it may be everything.", 0

